version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
      target: development
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:secret@mongodb:27017/mydatabase?authSource=admin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    container_name: mongodb
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')" -u admin -p secret --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    command: [--auth, --bind_ip_all]

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=secret
      - ME_CONFIG_MONGODB_AUTH_SOURCE=admin
      - ME_CONFIG_SITE_BASEURL=/
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongodb_data: